services:
  # Prometheus
  my-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # Tempo
  my-tempo:
    image: grafana/tempo
    container_name: my-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "9412:9411"

  # Loki
  my-loki:
    image: grafana/loki:latest
    container_name: my-loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki_data:/tmp/loki  # Montée du volume pour persister les données
    command: -config.file=/etc/loki/local-config.yaml

  # Grafana
  my-grafana:
    image: grafana/grafana
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=1234
