server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  wal:
    enabled: true
    dir: /tmp/wal
  chunk_target_size: 1048576

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/index
    cache_location: /tmp/cache
  # Utilisation du système de fichiers local pour stocker les objets (logs, index, etc.)
  filesystem:
    directory: /tmp/loki

schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb
      object_store: filesystem  # Indique l'utilisation du système de fichiers local pour les objets
      schema: v11
      index:
        prefix: loki_index_
